### ISSUE TITLE
Footer functionality to be updated

### ISSUE THREAD

**Issue by Cristilupchian** [Cristilupchian/Practical-JavaScript-ToDo-App#2]
All, Active and Completed buttons/links functionality to be added.

**Comment by Cristilupchian** [comment]
## TODO
*Task to be done*
* [ ] Show All ToDo Items button feature
* [ ] Show active todoitems button feature
* [ ] Show Completed todo items feature
🎉 👌
